# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Anton\Documents\PSoC Creator\Buzzer\Code for buzzer.cydsn\Code for buzzer.cyprj
# Date: Sun, 03 May 2026 21:18:49 GMT
#set_units -time ns
create_clock -name {Clock_1(routed)} -period 303041.66666666663 -waveform {0 151520.833333333} [list [get_pins {ClockBlock/dclk_0}]]
create_clock -name {Clock_2(routed)} -period 322583.33333333331 -waveform {0 161291.666666667} [list [get_pins {ClockBlock/dclk_1}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 7273 14545} -nominal_period 303041.66666666663 [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/clk_sync}] -edges {1 7743 15485} -nominal_period 322583.33333333331 [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {Clock_3} -source [get_pins {ClockBlock/clk_sync}] -edges {1 65537 131073} [list [get_pins {ClockBlock/dclk_glb_2}]]


# Component constraints for C:\Users\Anton\Documents\PSoC Creator\Buzzer\Code for buzzer.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Anton\Documents\PSoC Creator\Buzzer\Code for buzzer.cydsn\Code for buzzer.cyprj
# Date: Sun, 03 May 2026 21:18:46 GMT
